version: '3.6'
services:
  postgres:
    container_name: crud-api-db
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ../test/pgdata:/var/lib/postgresql/data
  redis:
    container_name: crud-api-cache
    image: "redis:6.2-alpine"
    restart: unless-stopped
    ports:
      - '6379:6379'
volumes:
  pgdata:
    external: true
    name:
      crud-api