linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode turn it off for now
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  #errcheck:
  #  exclude: /app/errcheck-exclude.txt
  funlen:
    lines: 150
    statements: 70
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    disable-tags:
      - opinionated
    disabled-checks:
      - ifElseChain
  gocyclo:
    min-complexity: 30
  lll:
    line-length: 300
  govet:
    disable:
      - composites

issues:
  exclude:
    - "ST1000:" # at least one file in a package should have a package comment (stylecheck)
    - "ST1003:" # should not use underscores in package names (stylecheck)
    - don't use an underscore in package name
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - lll
        - funlen
        - exportloopref
        - errcheck
        - dupl
        - gosec
    - path: mock/*
      linters:
        - lll
