// Code generated by MockGen. DO NOT EDIT.
// Source: query.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JavaHutt/crud-api/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockqueryRepository is a mock of queryRepository interface.
type MockqueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockqueryRepositoryMockRecorder
}

// MockqueryRepositoryMockRecorder is the mock recorder for MockqueryRepository.
type MockqueryRepositoryMockRecorder struct {
	mock *MockqueryRepository
}

// NewMockqueryRepository creates a new mock instance.
func NewMockqueryRepository(ctrl *gomock.Controller) *MockqueryRepository {
	mock := &MockqueryRepository{ctrl: ctrl}
	mock.recorder = &MockqueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockqueryRepository) EXPECT() *MockqueryRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockqueryRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockqueryRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockqueryRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockqueryRepository) Get(ctx context.Context, id int) (*model.SlowestQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.SlowestQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockqueryRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockqueryRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockqueryRepository) GetAll(ctx context.Context, page int, order string, statement model.QueryStatement) ([]model.SlowestQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, order, statement)
	ret0, _ := ret[0].([]model.SlowestQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockqueryRepositoryMockRecorder) GetAll(ctx, page, order, statement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockqueryRepository)(nil).GetAll), ctx, page, order, statement)
}

// Insert mocks base method.
func (m *MockqueryRepository) Insert(ctx context.Context, query model.SlowestQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockqueryRepositoryMockRecorder) Insert(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockqueryRepository)(nil).Insert), ctx, query)
}

// InsertBulk mocks base method.
func (m *MockqueryRepository) InsertBulk(ctx context.Context, queries []model.SlowestQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, queries)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockqueryRepositoryMockRecorder) InsertBulk(ctx, queries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockqueryRepository)(nil).InsertBulk), ctx, queries)
}

// Update mocks base method.
func (m *MockqueryRepository) Update(ctx context.Context, query model.SlowestQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockqueryRepositoryMockRecorder) Update(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockqueryRepository)(nil).Update), ctx, query)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockcache) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockcacheMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockcache)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *Mockcache) Get(ctx context.Context, id string) (*model.SlowestQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.SlowestQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcacheMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockcache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *Mockcache) Set(ctx context.Context, query *model.SlowestQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockcacheMockRecorder) Set(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockcache)(nil).Set), ctx, query)
}
