// Code generated by MockGen. DO NOT EDIT.
// Source: advertise.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JavaHutt/crud-api/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockadvertiseRepository is a mock of advertiseRepository interface.
type MockadvertiseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockadvertiseRepositoryMockRecorder
}

// MockadvertiseRepositoryMockRecorder is the mock recorder for MockadvertiseRepository.
type MockadvertiseRepositoryMockRecorder struct {
	mock *MockadvertiseRepository
}

// NewMockadvertiseRepository creates a new mock instance.
func NewMockadvertiseRepository(ctrl *gomock.Controller) *MockadvertiseRepository {
	mock := &MockadvertiseRepository{ctrl: ctrl}
	mock.recorder = &MockadvertiseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadvertiseRepository) EXPECT() *MockadvertiseRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockadvertiseRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockadvertiseRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockadvertiseRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockadvertiseRepository) Get(ctx context.Context, id int) (*model.Advertise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Advertise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockadvertiseRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockadvertiseRepository)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockadvertiseRepository) GetAll(ctx context.Context, page int, order string) ([]model.Advertise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, order)
	ret0, _ := ret[0].([]model.Advertise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockadvertiseRepositoryMockRecorder) GetAll(ctx, page, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockadvertiseRepository)(nil).GetAll), ctx, page, order)
}

// Insert mocks base method.
func (m *MockadvertiseRepository) Insert(ctx context.Context, advertise model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, advertise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockadvertiseRepositoryMockRecorder) Insert(ctx, advertise interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockadvertiseRepository)(nil).Insert), ctx, advertise)
}

// InsertBulk mocks base method.
func (m *MockadvertiseRepository) InsertBulk(ctx context.Context, ads []model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, ads)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockadvertiseRepositoryMockRecorder) InsertBulk(ctx, ads interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockadvertiseRepository)(nil).InsertBulk), ctx, ads)
}

// Update mocks base method.
func (m *MockadvertiseRepository) Update(ctx context.Context, advertise model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, advertise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockadvertiseRepositoryMockRecorder) Update(ctx, advertise interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockadvertiseRepository)(nil).Update), ctx, advertise)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *Mockcache) Get(ctx context.Context, id string) (*model.Advertise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Advertise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcacheMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockcache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *Mockcache) Set(ctx context.Context, ad model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, ad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockcacheMockRecorder) Set(ctx, ad interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*Mockcache)(nil).Set), ctx, ad)
}
