// Code generated by MockGen. DO NOT EDIT.
// Source: advertise.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JavaHutt/crud-api/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockadvertiseService is a mock of advertiseService interface.
type MockadvertiseService struct {
	ctrl     *gomock.Controller
	recorder *MockadvertiseServiceMockRecorder
}

// MockadvertiseServiceMockRecorder is the mock recorder for MockadvertiseService.
type MockadvertiseServiceMockRecorder struct {
	mock *MockadvertiseService
}

// NewMockadvertiseService creates a new mock instance.
func NewMockadvertiseService(ctrl *gomock.Controller) *MockadvertiseService {
	mock := &MockadvertiseService{ctrl: ctrl}
	mock.recorder = &MockadvertiseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadvertiseService) EXPECT() *MockadvertiseServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockadvertiseService) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockadvertiseServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockadvertiseService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockadvertiseService) Get(ctx context.Context, id int) (*model.Advertise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Advertise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockadvertiseServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockadvertiseService)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockadvertiseService) GetAll(ctx context.Context, page int, order string) ([]model.Advertise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, order)
	ret0, _ := ret[0].([]model.Advertise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockadvertiseServiceMockRecorder) GetAll(ctx, page, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockadvertiseService)(nil).GetAll), ctx, page, order)
}

// Insert mocks base method.
func (m *MockadvertiseService) Insert(ctx context.Context, advertise model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, advertise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockadvertiseServiceMockRecorder) Insert(ctx, advertise interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockadvertiseService)(nil).Insert), ctx, advertise)
}

// InsertBulk mocks base method.
func (m *MockadvertiseService) InsertBulk(ctx context.Context, ads []model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBulk", ctx, ads)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBulk indicates an expected call of InsertBulk.
func (mr *MockadvertiseServiceMockRecorder) InsertBulk(ctx, ads interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBulk", reflect.TypeOf((*MockadvertiseService)(nil).InsertBulk), ctx, ads)
}

// Update mocks base method.
func (m *MockadvertiseService) Update(ctx context.Context, advertise model.Advertise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, advertise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockadvertiseServiceMockRecorder) Update(ctx, advertise interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockadvertiseService)(nil).Update), ctx, advertise)
}
